# Generated by Django 3.2 on 2022-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0006_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
